# Generated by Django 2.2.7 on 2021-01-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_fio', models.CharField(max_length=255, verbose_name='Данные обучающегося')),
                ('test_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения теста')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Результат теста')),
                ('answers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответы')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Testing', verbose_name='Данные по тесту')),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
                'ordering': ('-id',),
            },
        ),
    ]
